### ISSUE TITLE
Search for text nodes with {p#} as title and auto update text

### ISSUE THREAD

**Issue by karbassi** [dgngulcan/pager#6]
It would be amazing to allow for the text node name to be labeled as "{p#}", allowing for the designer to reorder the frames and re-run the plugin, which updates the number (and order).

I'm assuming this filter needs to be updated.

https://github.com/dgngulcan/pager/blob/3c54fb3ca2094743d0fe0b3446bdd2b6b28f439d/src/code.ts#L15

**Comment by dgngulcan** [comment]
hi @karbassi , the label you suggested looks like the same as the existing label -- `{p#}`
can you elaborate please? thanks!

**Comment by karbassi** [comment]
Hello @dgngulcan, it's been a while since I wrote this issue. I honestly don't know what I meant by this. 

I should have written a better issue. Go ahead and delete this.
