### ISSUE TITLE
Nothing is happening

### ISSUE THREAD

**Issue by adamevers** [dgngulcan/pager#7]
Hello!

I'm trying to use the plugin but nothing ends up happening. I've included an export from the console when I run the plugin and [here](https://www.icloud.com/iclouddrive/0PD1VcqJFTA2mv5N-PzitYw0A#Figma_-_Pager_issue) is a link to a screen recording.

Any tips? 

Thank you!

[www.figma.com-1635986293278.log](https://github.com/dgngulcan/pager/files/7471492/www.figma.com-1635986293278.log)

**Comment by dgngulcan** [comment]
Hi @adamevers ! the video and the logs are very helpful! Sorry it took long to respond.

I just released an update, should fix the issue. let me know if it still persist.
